name: Echo

on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: event_name
        run: |
          echo "${{ github.event_name }}"
      - name: event
        run: |
          echo "${{ toJSON(github.event) }}"
          echo "${{ toJSON(github.event) }}" >> event.json
      - name: all
        run: |
          echo "${{ toJSON(github) }}"
          echo "${{ toJSON(github) }}" >> all.json
      - name: upload event
        uses: actions/upload-artifact@v4
        with:
          name: event
          path: event.json
      - name: upload all
        uses: actions/upload-artifact@v4
        with:
          name: all
          path: all.json
