name: Echo

on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: event_name
        run: |
          echo "${{ github.event_name }}"
      - name: event
        run: |
          cat >> event.json <<EOF
          ${{ toJSON(github.event) }}
          EOF
          echo < event.json
      - name: all
        run: |
          cat >> all.json <<EOF
          ${{ toJSON(github) }}
          EOF
          echo < all.json
      - name: upload event
        uses: actions/upload-artifact@v4
        with:
          name: event
          path: event.json
      - name: upload all
        uses: actions/upload-artifact@v4
        with:
          name: all
          path: all.json
